.nh
.TH "OGLE" "1" "May 2026" "" ""

.SH NAME
ogle - A TUI for monitoring Docker Compose projects.


.SH SYNOPSIS
\fBogle [flags]\fP


.SH DESCRIPTION
A TUI for monitoring Docker Compose projects.


.SH OPTIONS
\fB--config\fP=""
	config file (default is $HOME/.ogle/config)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ogle

.PP
\fB-f\fP, \fB--project-file\fP=""
	path to docker compose file


.SH SEE ALSO
\fBogle-version(1)\fP
