// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/ma-tf/ogle/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: path
func (_m *MockParser) Parse(path string) (*domain.Project, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Project, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Project); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: path
func (_m *MockParser) Validate(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
