// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/ma-tf/ogle/internal/domain"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(path string) (*domain.Project, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.Project, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.Project); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - path string
func (_e *MockParser_Expecter) Parse(path interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", path)}
}

func (_c *MockParser_Parse_Call) Run(run func(path string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(project *domain.Project, err error) *MockParser_Parse_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(path string) (*domain.Project, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockParser
func (_mock *MockParser) Validate(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParser_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockParser_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - path string
func (_e *MockParser_Expecter) Validate(path interface{}) *MockParser_Validate_Call {
	return &MockParser_Validate_Call{Call: _e.mock.On("Validate", path)}
}

func (_c *MockParser_Validate_Call) Run(run func(path string)) *MockParser_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParser_Validate_Call) Return(err error) *MockParser_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParser_Validate_Call) RunAndReturn(run func(path string) error) *MockParser_Validate_Call {
	_c.Call.Return(run)
	return _c
}
