// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamer creates a new instance of MockStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamer {
	mock := &MockStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamer is an autogenerated mock type for the Streamer type
type MockStreamer struct {
	mock.Mock
}

type MockStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamer) EXPECT() *MockStreamer_Expecter {
	return &MockStreamer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStreamer
func (_mock *MockStreamer) Close() {
	_mock.Called()
	return
}

// MockStreamer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStreamer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStreamer_Expecter) Close() *MockStreamer_Close_Call {
	return &MockStreamer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStreamer_Close_Call) Run(run func()) *MockStreamer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamer_Close_Call) Return() *MockStreamer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStreamer_Close_Call) RunAndReturn(run func()) *MockStreamer_Close_Call {
	_c.Run(run)
	return _c
}

// Next provides a mock function for the type MockStreamer
func (_mock *MockStreamer) Next() tea.Cmd {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func() tea.Cmd); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockStreamer_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockStreamer_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockStreamer_Expecter) Next() *MockStreamer_Next_Call {
	return &MockStreamer_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockStreamer_Next_Call) Run(run func()) *MockStreamer_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamer_Next_Call) Return(cmd tea.Cmd) *MockStreamer_Next_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockStreamer_Next_Call) RunAndReturn(run func() tea.Cmd) *MockStreamer_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockStreamer
func (_mock *MockStreamer) Start(ctx context.Context, containerName string) {
	_mock.Called(ctx, containerName)
	return
}

// MockStreamer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockStreamer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *MockStreamer_Expecter) Start(ctx interface{}, containerName interface{}) *MockStreamer_Start_Call {
	return &MockStreamer_Start_Call{Call: _e.mock.On("Start", ctx, containerName)}
}

func (_c *MockStreamer_Start_Call) Run(run func(ctx context.Context, containerName string)) *MockStreamer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamer_Start_Call) Return() *MockStreamer_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStreamer_Start_Call) RunAndReturn(run func(ctx context.Context, containerName string)) *MockStreamer_Start_Call {
	_c.Run(run)
	return _c
}
