// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

type MockScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanner) EXPECT() *MockScanner_Expecter {
	return &MockScanner_Expecter{mock: &_m.Mock}
}

// KnownFilenames provides a mock function for the type MockScanner
func (_mock *MockScanner) KnownFilenames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KnownFilenames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockScanner_KnownFilenames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KnownFilenames'
type MockScanner_KnownFilenames_Call struct {
	*mock.Call
}

// KnownFilenames is a helper method to define mock.On call
func (_e *MockScanner_Expecter) KnownFilenames() *MockScanner_KnownFilenames_Call {
	return &MockScanner_KnownFilenames_Call{Call: _e.mock.On("KnownFilenames")}
}

func (_c *MockScanner_KnownFilenames_Call) Run(run func()) *MockScanner_KnownFilenames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScanner_KnownFilenames_Call) Return(strings []string) *MockScanner_KnownFilenames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockScanner_KnownFilenames_Call) RunAndReturn(run func() []string) *MockScanner_KnownFilenames_Call {
	_c.Call.Return(run)
	return _c
}

// ScanAll provides a mock function for the type MockScanner
func (_mock *MockScanner) ScanAll(dir string) []string {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for ScanAll")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockScanner_ScanAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanAll'
type MockScanner_ScanAll_Call struct {
	*mock.Call
}

// ScanAll is a helper method to define mock.On call
//   - dir string
func (_e *MockScanner_Expecter) ScanAll(dir interface{}) *MockScanner_ScanAll_Call {
	return &MockScanner_ScanAll_Call{Call: _e.mock.On("ScanAll", dir)}
}

func (_c *MockScanner_ScanAll_Call) Run(run func(dir string)) *MockScanner_ScanAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScanner_ScanAll_Call) Return(strings []string) *MockScanner_ScanAll_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockScanner_ScanAll_Call) RunAndReturn(run func(dir string) []string) *MockScanner_ScanAll_Call {
	_c.Call.Return(run)
	return _c
}
