// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/lrstanley/bubblezone/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockZoneManager creates a new instance of MockZoneManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZoneManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZoneManager {
	mock := &MockZoneManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockZoneManager is an autogenerated mock type for the ZoneManager type
type MockZoneManager struct {
	mock.Mock
}

type MockZoneManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZoneManager) EXPECT() *MockZoneManager_Expecter {
	return &MockZoneManager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockZoneManager
func (_mock *MockZoneManager) Get(id string) *zone.ZoneInfo {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *zone.ZoneInfo
	if returnFunc, ok := ret.Get(0).(func(string) *zone.ZoneInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zone.ZoneInfo)
		}
	}
	return r0
}

// MockZoneManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockZoneManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockZoneManager_Expecter) Get(id interface{}) *MockZoneManager_Get_Call {
	return &MockZoneManager_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockZoneManager_Get_Call) Run(run func(id string)) *MockZoneManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockZoneManager_Get_Call) Return(zoneInfo *zone.ZoneInfo) *MockZoneManager_Get_Call {
	_c.Call.Return(zoneInfo)
	return _c
}

func (_c *MockZoneManager_Get_Call) RunAndReturn(run func(id string) *zone.ZoneInfo) *MockZoneManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Mark provides a mock function for the type MockZoneManager
func (_mock *MockZoneManager) Mark(id string, v string) string {
	ret := _mock.Called(id, v)

	if len(ret) == 0 {
		panic("no return value specified for Mark")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(id, v)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockZoneManager_Mark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mark'
type MockZoneManager_Mark_Call struct {
	*mock.Call
}

// Mark is a helper method to define mock.On call
//   - id string
//   - v string
func (_e *MockZoneManager_Expecter) Mark(id interface{}, v interface{}) *MockZoneManager_Mark_Call {
	return &MockZoneManager_Mark_Call{Call: _e.mock.On("Mark", id, v)}
}

func (_c *MockZoneManager_Mark_Call) Run(run func(id string, v string)) *MockZoneManager_Mark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockZoneManager_Mark_Call) Return(s string) *MockZoneManager_Mark_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockZoneManager_Mark_Call) RunAndReturn(run func(id string, v string) string) *MockZoneManager_Mark_Call {
	_c.Call.Return(run)
	return _c
}
